spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      eclipselink:
        ddl-generation: create-tables
        logging.level: FINE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring
    username: postgres
    password: postgres
    initialization-mode: always
  main:
    allow-circular-references: true
auth:
  server:
    base:
      url: http://localhost:8080
jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ